/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * aboutItemBoc.java
 *
 * Created on Dec 26, 2009, 9:13:07 PM
 */

package Utilities;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author mariuska
 */
public class aboutItemBox extends JFrame
{

	/** Creates new form aboutItemBoc */
	public aboutItemBox()
	{
		initComponents();

		//this.setSize(600, 600);
		//setSize(new Dimension(600, 600));
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		setResizable(false);
		setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/Utilities/resources/logo2.gif")));
		Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
		int x = (screen.width / 2) - (this.getWidth() / 2);
		int y = (screen.height / 2) - (this.getHeight() / 2);
		this.setLocation(x,y);
		this.setVisible(true);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		javax.swing.JLabel imageLabel = new javax.swing.JLabel();
		javax.swing.JLabel appTitleLabel = new javax.swing.JLabel();
		javax.swing.JLabel appDescLabel = new javax.swing.JLabel();
		javax.swing.JLabel versionLabel = new javax.swing.JLabel();
		javax.swing.JLabel appVersionLabel = new javax.swing.JLabel();
		javax.swing.JLabel vendorLabel = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/resources/logo2.gif"))); // NOI18N
		imageLabel.addComponentListener(new java.awt.event.ComponentAdapter()
		{
			public void componentResized(java.awt.event.ComponentEvent evt)
			{
				imageLabelComponentResized(evt);
			}
		});

		appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | java.awt.Font.BOLD, appTitleLabel.getFont().getSize()+4));
		appTitleLabel.setText("ChordFPG");

		appDescLabel.setText("<html>A distributed file-sharing System, based on chord paper, developed for the purposes of \"Distributed Systems\" lesson");

		versionLabel.setFont(versionLabel.getFont().deriveFont(versionLabel.getFont().getStyle() | java.awt.Font.BOLD));
		versionLabel.setText("Version:");

		appVersionLabel.setText("1.0");

		vendorLabel.setFont(vendorLabel.getFont().deriveFont(vendorLabel.getFont().getStyle() | java.awt.Font.BOLD));
		vendorLabel.setText("Developers:");

		jLabel1.setText("Gasparis Ioannis 3070040");

		jLabel2.setText("Pomonis Marios 3070151");

		jLabel3.setText("Fokas Xaralampos 3070176");

		jLabel5.setText("Georgios Ksulomenos");

		jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
		jLabel4.setText("Teacher:");

		jButton1.setText("Close");
		jButton1.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
		    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		    .addGap(0, 812, Short.MAX_VALUE)
		    .addGroup(layout.createSequentialGroup()
		              .addGap(6, 6, 6)
		              .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
		              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                        .addGroup(layout.createSequentialGroup()
		                                  .addComponent(appTitleLabel)
		                                  .addContainerGap())
		                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                                  .addGroup(layout.createSequentialGroup()
		                                          .addComponent(appDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
		                                          .addContainerGap())
		                                  .addGroup(layout.createSequentialGroup()
		                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                                                  .addComponent(jLabel4)
		                                                  .addComponent(vendorLabel)
		                                                  .addComponent(versionLabel))
		                                          .addGap(143, 143, 143)
		                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                                                  .addGroup(layout.createSequentialGroup()
		                                                          .addComponent(appVersionLabel)
		                                                          .addContainerGap())
		                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                                                          .addGroup(layout.createSequentialGroup()
		                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                                                                          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
		                                                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
		                                                                                  .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                                                                                  .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                                                                                  .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
		                                                                  .addContainerGap(43, Short.MAX_VALUE))
		                                                          .addGroup(layout.createSequentialGroup()
		                                                                  .addComponent(jLabel5)
		                                                                  .addContainerGap())))))))
		);
		layout.setVerticalGroup(
		    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		    .addGroup(layout.createSequentialGroup()
		              .addContainerGap()
		              .addComponent(appTitleLabel)
		              .addGap(17, 17, 17)
		              .addComponent(appDescLabel)
		              .addGap(18, 18, 18)
		              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                        .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
		                        .addComponent(appVersionLabel))
		              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                        .addComponent(jLabel1)
		                        .addComponent(vendorLabel))
		              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		              .addComponent(jLabel2)
		              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		              .addComponent(jLabel3)
		              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                        .addComponent(jLabel5)
		                        .addComponent(jLabel4))
		              .addGap(45, 45, 45)
		              .addComponent(jButton1)
		              .addContainerGap())
		    .addGroup(layout.createSequentialGroup()
		              .addGap(35, 35, 35)
		              .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void imageLabelComponentResized(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_imageLabelComponentResized
	{
		//GEN-HEADEREND:event_imageLabelComponentResized
		// TODO add your handling code here:
	}//GEN-LAST:event_imageLabelComponentResized

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
	{
		//GEN-HEADEREND:event_jButton1ActionPerformed
		this.dispose();
	}//GEN-LAST:event_jButton1ActionPerformed

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new aboutItemBox().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	// End of variables declaration//GEN-END:variables
}
