/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingsDialog.java
 *
 * Created on Dec 29, 2009, 1:46:14 AM
 */
package Utilities;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author haris
 */
public class SettingsDialog extends javax.swing.JDialog
{

	JFileChooser chooser;
	int fsPort;
	String shareFolder;
	/** Creates new form SettingsDialog */
	public SettingsDialog(java.awt.Frame parent, boolean modal)
	{
		super(parent, modal);
		initComponents();
		this.jTextField2.setEditable(false);
		this.shareFolder = null;

		setTitle("ChordFPG 1.0");
		this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/Utilities/resources/logo2.gif")));
		setResizable(false);
		Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
		int x = (screen.width / 2) - (this.getWidth() / 2);
		int y = (screen.height / 2) - (this.getHeight() / 2);
		this.setLocation(x,y);
	}


	public String getShareFolder()
	{
		return shareFolder;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		browseButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter()
		{
			public void windowClosing(java.awt.event.WindowEvent evt)
			{
				formWindowClosing(evt);
			}
		});

		jButton1.setText("Import");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter()
		{
			public void mouseReleased(java.awt.event.MouseEvent evt)
			{
				jButton1MouseReleased(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Arial", 1, 18));
		jLabel2.setText("ChordFPG Settings");

		jLabel3.setText("Share Folder");

		browseButton.setText("Browse");
		browseButton.addMouseListener(new java.awt.event.MouseAdapter()
		{
			public void mouseReleased(java.awt.event.MouseEvent evt)
			{
				browseButtonMouseReleased(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
		    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		    .addGroup(layout.createSequentialGroup()
		              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                        .addGroup(layout.createSequentialGroup()
		                                  .addGap(163, 163, 163)
		                                  .addComponent(jLabel2))
		                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
		                                  .addContainerGap()
		                                  .addComponent(jLabel3)
		                                  .addGap(59, 59, 59)
		                                  .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
		                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
		                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                                          .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
		                                          .addComponent(browseButton, javax.swing.GroupLayout.Alignment.TRAILING))))
		              .addContainerGap())
		);
		layout.setVerticalGroup(
		    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		    .addGroup(layout.createSequentialGroup()
		              .addGap(6, 6, 6)
		              .addComponent(jLabel2)
		              .addGap(30, 30, 30)
		              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                        .addComponent(jLabel3)
		                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                        .addComponent(browseButton))
		              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		              .addComponent(jButton1)
		              .addContainerGap(20, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void browseButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_browseButtonMouseReleased
	{
		//GEN-HEADEREND:event_browseButtonMouseReleased
		chooser = new JFileChooser();
		chooser.setDialogTitle("Share Directory");
		chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		chooser.setAcceptAllFileFilterUsed(false);
		chooser.showOpenDialog(this);

		if (chooser.getSelectedFile() != null)
		{
			this.jTextField2.setText(chooser.getSelectedFile().getAbsolutePath());
			this.shareFolder = chooser.getSelectedFile().getAbsolutePath();
		}
		else
		{
			jTextField2.setText("");
		}



	}//GEN-LAST:event_browseButtonMouseReleased

	private void jButton1MouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton1MouseReleased
	{
		//GEN-HEADEREND:event_jButton1MouseReleased

		if (chooser == null || chooser.getSelectedFile() == null)
		{
			JOptionPane.showMessageDialog(this,"Please select a folder." , "ChordFPG said:" , JOptionPane.ERROR_MESSAGE);
		}
		else
		{
			this.dispose();
		}
		//this.fsPort = Integer.parseInt(this.jTextField1.getText());


	}//GEN-LAST:event_jButton1MouseReleased

	private void formWindowClosing(java.awt.event.WindowEvent evt)  //GEN-FIRST:event_formWindowClosing
	{
		// TODO add your handling code here:
		if (chooser != null)
		{
			JOptionPane.showMessageDialog(this,"You lose :( ... bb" , "ChordFPG said:" , JOptionPane.ERROR_MESSAGE);
			System.exit(0);
		}
	}//GEN-LAST:event_formWindowClosing



	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton browseButton;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration//GEN-END:variables
}
